[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py
addopts = --nomigrations --reuse-db -q
pythonpath = .

env =
    DEBUG=False
    TESTING=True
    postgresql=False
    SECRET_KEY=django-insecure-test-key-only-for-pytest-1234567890abcdef