# Generated by Django 5.1.15 on 2026-07-20 20:59

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_remove_apartment_apartment_description_min_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="land",
            field=models.CharField(help_text="Federal state (Bundesland)", max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid postal code.", regex="^\\d{4,10}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="housing_type",
            field=models.CharField(
                choices=[
                    ("APARTMENT", "Apartment"),
                    ("HOUSE", "House"),
                    ("STUDIO", "Studio"),
                    ("ROOM", "Room"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.01"), message="Price must be greater than zero."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="rooms",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Must have at least 1 room."
                    ),
                    django.core.validators.MaxValueValidator(
                        5, message="Too many rooms — please check the value, maximum is 5."
                    ),
                ]
            ),
        ),
    ]
