
    name: Django CI/CD Pipeline

    on:
      push:
        branches: [ "main", "15.07" ]
      pull_request:
        branches: [ "main" ]

    jobs:
      test:
        runs-on: ubuntu-latest

        steps:
          - name: Copy Repository Contents
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.12'

          - name: Install Dependencies
            run: |
              python -m pip install --upgrade pip
              pip install ruff pytest pytest-django Faker
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

          - name: Run Ruff Linter
            run: ruff check .

          - name: Run Pytest
            env:
              PYTHONPATH: .
              SECRET_KEY: 'django-insecure-ci-test-key-just-for-running-pytest-in-github'
            run: pytest